
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.chopper.dart"
    - "**/*.freezed.dart"
    - "**/*.g.dart"
    - "**/*.gen.dart"
    - "**/*.mocks.dart"
    - "lib/gen/**"
    - "lib/models/**"
    - "lib/amplifyconfiguration.dart"
    - "widgetbook/**"
  errors:
    todo: ignore
    prefer_const_constructors: info
    missing_required_param: error
    missing_return: error
    must_be_immutable: error
    unnecessary_const: error